eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-user:eureka-pass@localhost:8777/eureka/



#     region : default

#     registryFetchIntervalSeconds : 5
