eureka:
 client:
   region : default
   registryFetchIntervalSeconds : 5
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://eureka-user:eureka-pass@localhost:8762/eureka/
 instance:
   hostname: localhost

