eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-user:eureka-pass@localhost:8778/eureka/



#     region : default
#eureka-user:eureka-pass@
#     registryFetchIntervalSeconds : 5
